export const appRoutes = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  createProject: "/upload",
  upload: "/upload",
  projects: "/projects",
  boqGeneration: "/boq-generation",
  pdfGeneration: "/pdf-generation",
  workspace: (projectId: string) => `/workspace/${projectId}`,
  workflowStep: (projectId: string, step: string) => `/workspace/${projectId}/${step}`,
  workflowUpload: (projectId: string) => `/workspace/${projectId}/upload`,
  workspaceBoq: (projectId: string) => `/workspace/${projectId}/boq`,
  workspaceReviewTypes: (projectId: string) => `/workspace/${projectId}/review/classifications`,
  workspaceBoqSetup: (projectId: string) => `/workspace/${projectId}/boq/setup`,
  workspaceBoqTemplates: (projectId: string) => `/workspace/${projectId}/boq/templates`,
  workspaceBoqExports: (projectId: string) => `/workspace/${projectId}/boq/exports`,
  admin: "/admin",
  adminOrganizations: "/admin/organizations",
  adminSuperAdmins: "/admin/super-admins",
  adminSubscriptions: "/admin/subscriptions",
  adminBilling: "/admin/billing",
  adminAuditLogs: "/admin/audit-logs",
  adminSettings: "/admin/settings",
  organization: "/organization",
  organizationMembers: "/organization/members",
  organizationRoles: "/organization/roles",
  organizationBilling: "/organization/billing",
  organizationSettings: "/organization/settings",
  accountProfile: "/account/profile",
  accountSettings: "/account/settings",
  accountSecurity: "/account/security",
  notifications: "/notifications",
  usage: "/usage",
};
