"use client";

import { useEffect, useRef, useState } from "react";
import { Button } from "@/shared/components/Button";
import type { BoqPlaceholder, BoqTemplateItem } from "../types";
import { ConditionalRuleBuilder, normalizeRules } from "./ConditionalRuleBuilder";
import { FormulaBuilder, normalizeFormula } from "./FormulaBuilder";
import { PlaceholderPicker } from "./PlaceholderPicker";
import { TemplatePreview } from "./TemplatePreview";

const emptyItem: Omit<BoqTemplateItem, "id" | "template_id"> = { name: "New item", element_type: "door", section_code: "5D", section_name: "Doors", unit: "nr", description_template: "[TYPE_CODE] – [MATERIAL] item [WIDTH] × [HEIGHT] mm.", keywords: [], template_mode: "standard", conditional_rules: [], formula: { type: "quantity_x_rate" }, sort_order: 100, is_active: true };

export function TemplateItemEditor({ item, placeholders, preview, saving, onSave, onDelete, onPreview }: { item: BoqTemplateItem | null; placeholders: BoqPlaceholder[]; preview: string; saving: boolean; onSave: (payload: Omit<BoqTemplateItem, "id" | "template_id">) => Promise<void>; onDelete?: () => Promise<void>; onPreview: () => Promise<void> }) {
  const [form, setForm] = useState<Omit<BoqTemplateItem, "id" | "template_id">>(emptyItem);
  const textarea = useRef<HTMLTextAreaElement | null>(null);
  useEffect(() => setForm(item ? { name: item.name, element_type: item.element_type, section_code: item.section_code, section_name: item.section_name, unit: item.unit, description_template: item.description_template, keywords: item.keywords, template_mode: item.template_mode, conditional_rules: item.conditional_rules, formula: item.formula, sort_order: item.sort_order, is_active: item.is_active } : emptyItem), [item]);
  function insertToken(token: string) { const node = textarea.current; const start = node?.selectionStart ?? form.description_template.length; const end = node?.selectionEnd ?? start; const next = `${form.description_template.slice(0, start)}${token}${form.description_template.slice(end)}`; setForm({ ...form, description_template: next }); }
  return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Template item name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><label><span className="text-xs font-semibold uppercase text-slate-500">Element type</span><select className="input mt-2 w-full" value={form.element_type} onChange={(event) => setForm({ ...form, element_type: event.target.value as BoqTemplateItem["element_type"] })}>{["door","window","wall_external","wall_internal","floor","manual"].map((value) => <option key={value}>{value}</option>)}</select></label><Field label="Section code" value={form.section_code || ""} onChange={(value) => setForm({ ...form, section_code: value })} /><Field label="Section name" value={form.section_name} onChange={(value) => setForm({ ...form, section_name: value })} /><Field label="Unit" value={form.unit} onChange={(value) => setForm({ ...form, unit: value })} /><label><span className="text-xs font-semibold uppercase text-slate-500">Sort order</span><input className="input mt-2 w-full" type="number" value={form.sort_order} onChange={(event) => setForm({ ...form, sort_order: Number(event.target.value) })} /></label></div>
    <label className="block"><span className="text-xs font-semibold uppercase text-slate-500">Description template</span><textarea ref={textarea} className="input mt-2 min-h-28 w-full" value={form.description_template} onChange={(event) => setForm({ ...form, description_template: event.target.value })} /></label><PlaceholderPicker placeholders={placeholders} onPick={insertToken} />
    <label className="block"><span className="text-xs font-semibold uppercase text-slate-500">Keywords</span><input className="input mt-2 w-full" value={form.keywords.join(", ")} onChange={(event) => setForm({ ...form, keywords: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></label>
    <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><span className="text-sm font-medium">Conditional template rules</span><input type="checkbox" checked={form.template_mode === "conditional"} onChange={(event) => setForm({ ...form, template_mode: event.target.checked ? "conditional" : "standard" })} /></label>{form.template_mode === "conditional" ? <ConditionalRuleBuilder value={!Array.isArray(form.conditional_rules) && form.conditional_rules?.branches ? normalizeRules(form.conditional_rules) : normalizeRules()} onChange={(value) => setForm({ ...form, conditional_rules: value })} /> : null}<FormulaBuilder value={normalizeFormula(form.formula)} onChange={(formula) => setForm({ ...form, formula })} /><TemplatePreview description={preview} />
    <div className="flex flex-wrap justify-between gap-2"><div>{onDelete ? <Button variant="danger" disabled={saving} onClick={() => void onDelete()}>Delete item</Button> : null}</div><div className="flex gap-2"><Button variant="secondary" disabled={saving || !item} onClick={() => void onPreview()}>Preview</Button><Button disabled={saving || !form.name || !form.description_template} onClick={() => void onSave(form)}>{item ? "Save item" : "Create item"}</Button></div></div>
  </div>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span className="text-xs font-semibold uppercase text-slate-500">{label}</span><input className="input mt-2 w-full" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
